### ISSUE TITLE
404 error on webpage

### ISSUE THREAD

**Issue by bryanrscott** [OHI-Science/ohi-science.github.io#36]
Hi

On the page http://ohi-science.org/ohi-global/download.html the link to download the data for 2018 is not working?

https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/global2018/OHI_final_formatted_scores_2018-11-28.csv

cheers
Bryan

**Comment by Melsteroni** [comment]
Thanks for letting us know about this broken link.  

The issue is now resolved.
