### ISSUE TITLE
Redirect Index Page

### ISSUE THREAD

**Issue by ThomasThelen** [OHI-Science/ohi-science.github.io#42]
This issue probably belongs in this repository instead of [here](https://github.com/OHI-Science/OHI-website/issues/116). We'd like to redirect the landing page for ohi-science to the new oceanhealthindex.org.

@Melsteroni is it okay for me to go ahead and create a pull request to do so? I'd modify `index.html` with a blurb of javascript that will redirect the user.

**Comment by Melsteroni** [comment]
Will creating a pull request result in not seeing the current
oceanhealthindex.org website?

**Comment by ThomasThelen** [comment]
Accepting & merging the pull request will mean that anyone visiting https://ohi-science.org/ will get redirected to oceanhealthindex.org

**Comment by Melsteroni** [comment]
I think that should be fine.  Is there any way to still view ohi-science.org
?

**Comment by ThomasThelen** [comment]
All of the other pages on ohi-science.org will be accessible, for example `https://ohi-science.org/projects/` and `https://ohi-science.org/Data`. _But_. Whenever anyone goes to the root landing page of ohi-science, `ohi-science.org`, they'll be redirected over to oceanhealthindex.org.

If you want users to be able to view `ohi-science.org` _and_ see oceanhealthindex.org I should be able to open it in a new tab rather than redirect the main page. This might be a little confusing to users though (I don't recall visiting sites that do this).

Another alternative is to have a link somewhere on the main landing page to oceanhealthindex.org.

**Comment by Melsteroni** [comment]
I think it seems fine for the root landing page to redirect to
oceanhealthindex.org.  I mostly wanted to make sure we could still see the
webpages in case someone needs to see something specific over there.  And,
it sounds like they will be.

**Comment by Melsteroni** [comment]
(with a slightly different link)
